server:
  port: 8000

# default
spring:
  application:
    name: user
  profiles:
    group:
      default:
        - devcore
      dev:
        - devcore
      prod:
        - core
logging:
  level:
    com.example.module.config.aop : debug




